airlift/airbase

CHANGES.md, pom.xml
It fixes a race condition that can cause requests to hang
=> Update to Jetty 9.2.11.v20150529

CHANGES.md, README.md, pom.xml
Earlier versions are not compatible with Java 9
=> Update to bval 1.1.1

CHANGES.md, pom.xml
This version resolves dependencies in parallel and is much faster.
=> Update dependency-versions-check to 2.0.4

CHANGES.md, README.md, pom.xml
The forkMode parameter is deprecated in Surefire.
=> Remove air.test.fork-mode property

.travis.yml, CHANGES.md, airbase/pom.xml
Example failure:
```
$ mvn validate
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.airlift:slice:jar:0.37-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.openjdk.jol:jol-core:jar -> duplicate declaration of version 0.2 @ line 45, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------------------------< io.airlift:slice >--------------------------
[INFO] Building slice 0.37-SNAPSHOT
[INFO] --------------------------------[ jar …
```
=> Do not allow duplicate dependencies in POMs

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
This check does not work as expected for multidimensional arrays.
=> Do not enforce whitespace before array initializers

CHANGES.md, airbase/pom.xml
Due to https://youtrack.jetbrains.com/issue/IDEA-194601, when using
```
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
<parameters>true</parameters>
...
```
parameters are not generated when code is compiled in IntelliJ.
Also, manual IDE configuration is not an option, since the configuration
gets reset each time IDE auto-loads pom changes.
=> Generate parameters names reliably

CHANGES.md, airbase/pom.xml
This avoids different exception messages under different system
languages.
=> Set the JVM locale fix to en-US when running tests

CHANGES.md, airbase/pom.xml
This fixes skipping sources with `-Dmaven.source.skip=true`. The flag is
said documented as supported "since 2.2", but was not effective in 2.2.1.
=> Update maven-source-plugin to 3.0.1

.travis.yml
Oracle Java 8 is no longer available on Travis.
=> Replace Oracle Java 8 with OpenJDK

.travis.yml
Hi all,
I'd like to propose the following changes:
- Move from Oracle to OpenJDK completely. Something is off with the Oracle builders of Travis: https://travis-ci.org/airlift/airbase/jobs/592909648
- Set JDK14 Early Access to allow failure. This will run the build but ignore the result. Therefore the badge on the repository will be green, looking all good won't upset any users. The current issue that we're seeing is spotted by Gradle and Groovy as well and seems to be something with the JDK: https://github.com/gradle/gradle/issues/10248
Cheers, Fokko
Supersedes https://github.com/airlift/airbase/pull/188
=> Do not report failures for early access JDK

CHANGES.md, airbase/pom.xml
Dear maintainers. 
I'd like to bump Jackson to 2.9.9 and databind to 2.9.9.3 due to discovered CVE's in databind: https://www.cvedetails.com/vulnerability-list.php?vendor_id=15866&product_id=42991&version_id=&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=23&sha=5425c8855ccdf6005f8b83f6d90fed738cf8a8e8
This triggered my vulnerability scanner, and it would be great to get this patched. Bumping to 2.10 isn't possible yet since we're supporting Java8. Would it be possible to create a new release as well? So I can downstream this in other projects. Please let me know.
Cheers, Fokko
=> Bump Jackson to 2.9.10

airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
We want to allow lambdas like
() -> { throw new RuntimeException(); }
=> Fix lambda opening brace check

CHANGES.md, airbase/pom.xml
The primary motivation for this checker seems to have been long since
fixed in Maven, and the other warnings it provides are not useful.
=> Remove dependency:analyze-dep-mgt check

CHANGES.md, airbase/pom.xml
slf4j to 1.7.30 (http://www.slf4j.org/news.html)
jackson to 2.10.3 (https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.3)
guice to 4.2.3 (https://github.com/google/guice/wiki/Guice423)
=> Bump dependencies

CHANGES.md, airbase/pom.xml
Tested on PrestoSQL (`./mvnw -pl '!presto-server-rpm,!presto-docs,!presto-proxy,!presto-verifier' clean install -TC2 -nsu -DskipTests`)
Before:
```
[INFO] Total time:  04:43 min (Wall Clock)
```
After:
```
Total time:  03:26 min (Wall Clock)
```
All credit goes to @hashhar (see https://github.com/prestosql/presto/pull/5817)
=> Configure git-commit-id-plugin to reduce build times

CHANGES.md, airbase/pom.xml
I've tested it by building Trino and running product tests from the build.
Slight change is needed in Trino to make it work:
```
diff --git a/testing/trino-benchto-benchmarks/pom.xml b/testing/trino-benchto-benchmarks/pom.xml
index 43c4ba195d..6eae23374d 100644
--- a/testing/trino-benchto-benchmarks/pom.xml
+++ b/testing/trino-benchto-benchmarks/pom.xml
@@ -85,7 +85,9 @@
<plugin>
<artifactId>maven-assembly-plugin</artifactId>
<configuration>
-                    <descriptor>src/assembly/benchmarks.xml</descriptor>
+                    <descriptors>
+                        <descriptor>src/assembly/benchmarks.xml</descriptor>
+                    </descriptors>
<finalName>presto-benchto-benchmarks-package-${project.version}</finalName>
<appendAssemblyId>false</appendAssemblyId> …
```
=> Update maven plugins

CHANGES.md, airbase/pom.xml
The profile is not being kept updated. This will let downstream projects
set same-named profile without inheriting any unwanted outdated
configuration.
=> Remove errorprone-compiler profile

CHANGES.md, airbase/pom.xml
The difference between `gnu` and `posix` tar formats is explained here: https://www.gnu.org/software/tar/manual/html_section/tar_67.html#Formats
I think that we are good with switch to `posix` tar mode.
cc @electrum @findepi
=> Use posix tar mode in assembly-plugin

airbase/pom.xml
Allows us to identify false positive cases due to misconfiguration
for tests
=> Fail build if no tests are executed

CHANGES.md, airbase/pom.xml
Typical usage would be
```xml
<air.javadoc.lint>all,-missing</air.javadoc.lint>
```
=> Allow using commas in air.javadoc.lint

CHANGES.md, airbase/pom.xml
Otherwise, it causes a build failure unless the project includes
it directly (i.e., as a consequence of containing junit-based tests)
=> Add junit dependency to surefire plugin

airbase/pom.xml
Log4j2 versions older than 2.15.0 are vulnerable to the Log4Shell RCE
(CVE-2021-44228).
FYI @martint @electrum
=> Enforce vulnerable log4j2 versions aren't used

airbase/pom.xml
The latest version of the extra-enforcer-rules plugin now enforces
dependencies of the "provided" scope. The osgi and jaxb-runtime
dependencies now creating a conflict with other dependencies in the
project
=> Exclude conflicting dependencies

CHANGES.md, airbase/pom.xml
Fixes an issue where it will report an error for string literals that
contain spaces at the end.
=> Update checkstyle to 9.2

CHANGES.md, airbase/pom.xml
This breaks the standard `skipTests` property.
=> Remove `air.test.skip` property

CHANGES.md, airbase/pom.xml
This version brings compatibility with JDK17+
See: https://github.com/google/guice/wiki/Guice510
=> Update guice to 5.1.0

airbase/pom.xml
Enable check plugins only when matching `air.check.skip-*` properties are false. This is supposed to avoid any unnecessary initialization overhead. Another minor improvement is that Maven output is not polluted with unused plugins.
I noticed #69 and I've seen similar issues when disabling the dependency plugin so this is the only check plugin that's skipped using configuration.
Tested roughly (only 3 runs of every goal) by running the following goals in [the Trino](https://github.com/trinodb/trino) project, on an otherwise idle r5.large instance:
* clean
* clean install
* install - doesn't require warm-up since it's run after `clean install`
To make tests quicker, I skip the 3 largest modules, this still leaves out 76 modules to be built.
```
flags='--strict-checksums -V -DskipTests …
```
=> Only enable check plugins if air.check.skip-* is false

CHANGES.md, airbase/pom.xml
Define an empty default value for the `argLine` property, required when `air.check.skip-jacoco` is true. This was introduced in the 120 version, where unused plugins are disabled completely.
=> Define default `argLine` property

CHANGES.md, airbase/pom.xml
Profile activation is performed by Maven before resolving properties,
so inherited properties cannot be used for it. To optimize for the most
common scenario, only completely disable check plugins when all are
skipped. When single plugins are skipped, it will be done in their
configuration.
=> Enable check plugins unless air.check.skip-all is set

CHANGES.md, airbase/pom.xml
All credit to @findinpath for finding this.
See for source https://github.com/trinodb/trino/pull/11563#issuecomment-1072302541
cc: @findinpath @findepi
=> Allow configuring if existing headers should be skipped in license check

CHANGES.md, airbase/pom.xml
This version is compatible with JDK 16+:
```
Release Notes - Maven Dependency Plugin - Version 3.3.0
** Bug
* [MDEP-679] - mvn dependency:analyze detected wrong transitive
dependency
* [MDEP-742] - dependency plugin does not work with JDK 16
* [MDEP-752] - skip dependency analyze in ear packaging
* [MDEP-753] - Non-test dependency reported as Non-test scoped test
only dependency
* [MDEP-759] - 'Dependency not found' with 3.2.0 and Java-17 while
analyzing
* [MDEP-761] - Tree plugin does not terminate with 3.2.0
* [MDEP-769] - Minor improvement - continue
* [MDEP-774] - analyze-only failed: PermittedSubclasses requires ASM9
* [MDEP-781] - Broken Link to "Introduction to Dependency Mechanism
Page"
* [MDEP-783] - TreeMojo docs say scope doesn't work due to MSHARED-4
* [MDEP-786] - Sealed …
```
=> Update maven-dependency-plugin to 3.3.0

CHANGES.md, airbase/pom.xml
The new version includes https://github.com/apache/maven-surefire/pull/407 which should reduce memory usage in CI and help avoid failures caused by running out of memory.
=> Update Surefire plugin

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
For example a comment like below was previously flagged as invalid.
```
/**
* A class that implements ...
```
=> Allow using "extends" and "implements" in a Java comment

CHANGES.md, airbase/pom.xml
This moves primarily the `user.language` and `user.region` from `systemPropertyVariables` to explicit property setting on the JVM. These two methods to set them are supposed to be the same, but passing via system properties does not actually work. Which is annoying, because when the are set in both ways, Surefire complains about it:
```
[WARN] The system property user.language is configured twice! The property appears in <argLine/> and any of <systemPropertyVariables/>, <systemProperties/> or user property.
[WARN] The system property user.region is configured twice! The property appears in <argLine/> and any of <systemPropertyVariables/>, <systemProperties/> or user property.
```
It seems that the `user.timezone` actually works as expected, but is moved along with the other two for …
=> Fix the way locale information is passed to Surefire

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
Lot of dependencies shade Apache code and it's easy to import from them
by mistake which often breaks once dependencies are updated and have
improved their exclusions/shading.
=> Disallow shaded org.apache imports

CHANGES.md, airbase/pom.xml
The `argLine` property is used by Jacoco to store the JVM commands which enable its agent. It is initialized by the Jacoco plugin, then used in the Surefire configuration. But when Jacoco is disabled (e.g. using the `air.check.skip-jacoco` property), the `argLine` property is not initialized, and if we don't take additional measures, it will appear as literal `${argLine}` in Surefire's JVM arguments line, which may cause trouble with some tools. The way it was handled previously was that there was an additional profile, which was supposed to be activated when Jacoco was disabled, and which initialized the `argLine` property to empty, allowing Maven to properly interpolate it in the Surefire configuration.
There was one problem with this solution, though - these are system properties, not …
=> Always declare empty argLine

CHANGES.md, airbase/pom.xml
Update slf4j to be able to update testcontainers to the latest version, since it also depends on slf4j.
Update joda-time to the latest version. This brings back some timezones removed earlier: https://www.joda.org/joda-time/changes-report.html#a2.10.14
=> Update dependencies: slf4j, joda-time

CHANGES.md, airbase/pom.xml
Tested on current Trino master. Does not yield new violations for existing code.
=> Upgrade checkstyle to 10.3.2

CHANGES.md, airbase/pom.xml
I browsed the changelog and I didn't see any breaking changes, mostly updated dependencies, fixes, and new checks. I also built Trino with this snapshot of Airbase and it was successful.
Same for modernizer.
=> Update spotbugs-annotations and modernizer version

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
Enforce interface methods have no redundant modifiers (like `public`). The checkstyle's `RedundantModifier` applies to interface and classes as well. In private classes it flags `public` methods as having redundant modifiers. It is technically correct, but some projects (like Trino) choose to use `public` in private classes for documenting the "internal interface" of a class. Thus, the check is suppressed inside class definitions (but still applies to interfaces inside classes).
Fixes https://github.com/airlift/airbase/issues/174
=> Enforce no redundant modifiers in interfaces

CHANGES.md, airbase/pom.xml
The Jetty packaging of the servlet API is newer, contains bug fixes, and per the Jetty team is required when using Jetty 10.
=> Use jetty-servlet-api instead of javax.servlet-api

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
I.e. a line that IntelliJ formatter would insert.
=> Require empty line before javadoc tags

CHANGES.md, airbase/pom.xml
As the configured error message says, providing a version is important for build stability.
Also, bump Enforcer to the latest version.
=> Enable requirePluginVersions in enforcer plugin

CHANGES.md, airbase/pom.xml
This module guarantees that we declare all the possible Jackson modules and we don't have to enumerate them. Previously we missed some important ones, like `jackson-dataformat-xml`.
=> Pin Jackson module versions using the official BOM

CHANGES.md, airbase/pom.xml
The Kotlin BOM is needed to ensure that the various Kotlin dependencies dragged in by OkHttp have the same version. OkHttp is used by the OpenTelemetry exporters.
=> Add OpenTelemetry dependencies

airbase/pom.xml
Maven now warns about this:
```
[WARN] Parameter 'inputEncoding' (user property 'encoding') is read-only, must not be used in configuration
=> Remove read-only inputEncoding parameter from PMD

CHANGES.md, airbase/pom.xml
This PR updates bunch of dependencies and plugins to the newest versions.
Tested locally in Trino master - there are no API changes that require code changes. Plugins doesn't need configuration updates. Updated checkstyle is not introducing new violations.
I've left maven-release and gpg plugins outdated as I don't have means to test them properly.
Trino builds with just:
```
<parent>
<groupId>io.airlift</groupId>
<artifactId>airbase</artifactId>
<version>139-SNAPSHOT</version>
</parent>
```
=> [Spring cleaning] Plugins and dependencies updates

CHANGES.md, airbase/pom.xml
Some time ago, some properties were moved to `argLine` because Surefire incorrectly passes the `user.language` and `user.region` system properties to the tests. At that time, the `user.timezone` also got along for the ride, but it turns out, that that latter property *is* passed correctly. So while it works for Maven and Surefire, moving it into `argLine` causes IntelliJ IDEA to not pick it up, which in turn means that some tests are not working properly when executed inside the IDE. We can move it safely back, as it improves quality of life.
This reverts parts of commit d4630aa6547a64c7112f2bf133138d7d83b6d1a8.
=> Fix running timezone-sensitive tests in IntelliJ IDEA

CHANGES.md, airbase/pom.xml
This version recognized JDK 21 classes correctly (previous one fails on JDK 21 with target 21)
=> Update extra-enforcer-rules to 1.7.0

CHANGES.md, airbase/pom.xml
Bumps only patch versions, might be required by some libraries that already use latest patch. 
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
=> Update jackson to 2.15.2

CHANGES.md, airbase/pom.xml
This release, among other things, natively depends on ASM 9.5 with support for new opcodes in Java 21, but we'll keep the ASM version override in case we need a blanket ASM upgrade in the future.
=> Update maven-shade-plugin to 3.5.0

airbase/pom.xml
Quoting the `<reason>`:
> These classes were introduced to overcome type inference issues in
> Java 8, but the regular `org.assertj.core.api.Assertions` works just
> fine and has a richer API.
=> Ban two Assertions classes from AssertJ

pom.xml
With the current setup any inheriting project has to override developers .. otherwise they get
the following in the effective pom: 
```
<developers>
<developer>
<name>Airlift</name>
</developer>
</developers>
```
Which is wrong. This is currently the case in Trino for example.
The new setup pulls the scm url into place and results in a correct URL to the github or whatever repo and has a generic sentence instead of referencing airlift. Here is the effective pom for this project itself:
```
<developers>
<developer>
<name>Numerous contributors, see scm log</name>
<url>https://github.com/airlift/airbase</url>
</developer>
</developers>
```
It uses the property so for example in Trino we would get this:
```
<developers>
<developer>
<name>Numerous contributors, see scm log</name> …
```
=> Improve developers section

airbase-policy/pom.xml
Removes warning:
```
[INFO] --- resources:3.3.1:testResources (default-testResources) @ airbase-policy ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/mateuszgajewski/Projects/src/github.com/airlift/airbase/airbase-policy/src/test/resources
```
=> Suppress maven warning on platform dependant build

CHANGES.md, airbase/pom.xml
There is a regression in logback 1.4.9 which causes Trino tests to fail due to timeouts. The root cause is still to be investigated.
Related: https://github.com/trinodb/trino/pull/19194
Trino logback update test: https://github.com/trinodb/trino/pull/19207
=> Downgrade logback to 1.4.8

CHANGES.md, airbase/pom.xml
Bump `git-commit-id-maven-plugin` to [version 7.0.0](https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v7.0.0), which most notably fixes an issue where the plugin doesn't work properly in Git worktrees. See https://github.com/trinodb/trino/issues/18027 for more details on the issue. This will allow consumers to get rid of workarounds like the one introduced to Trino in https://github.com/trinodb/trino/pull/18046
=> Bump git-commit-id-maven-plugin to 7.0.0 to fix git worktree issue

CHANGES.md, airbase/pom.xml
2.8.0 requires maven 3.9.6 and doesn't work with mvnd in the process.
=> Downgrade modernizer to 2.7.0

CHANGES.md, airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
Forbid these
new int[]{...
new int[]    {....
Extracted from https://github.com/airlift/airbase/pull/389
=> Forbid no/abundant whitespace before array initializer

airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
This check prevents a modern Java idiom (and likely future idioms). E.g.
```
public sealed interface Choice
{
record GoodChoice(...)
implements Choice
{
}
record BadChoice(...)
implements Choice
{
}
}
```
The previous purpose of `InterfaceIsType` is arguably out of date anyway. It's better to use an interface for utility containers, etc.
=> Remove `InterfaceIsType` checkstyle module

airbase/pom.xml
Some of the maven plugins (like error_prone) have moved to JDK 17.
=> Require JDK 17

airbase/pom.xml
Checkstyle doesn't yet support them: https://github.com/checkstyle/checkstyle/issues/8240
=> Ignore module-info.java in checkstyle

airbase/pom.xml
This makes it easier to override some of the checkstyle configuration
=> Move checkstyle configuration from execution to plugin
