airlift/airbase

pom.xml

Update guava to 0.20

---

CHANGES.md
README.md
pom.xml

The plugin is not compatible with Takari lifecycle or Provisio.

Revert using Nexus Staging plugin

---

CHANGES.md
pom.xml

It is not compatible with Surefire 2.20.1

Remove support for JUnit 5

---

pom.xml

The latest Logback contains fixes to reduce the lock contention
while logging events to a file.

Upgrade Logback to v1.2.3

---

CHANGES.md
pom.xml

This fixes compatibility with Java 9.

Update Javadoc plugin to 3.0.0

---

CHANGES.md
airbase/pom.xml

Upgrade JMH to 1.20

---

CHANGES.md
airbase/pom.xml

-  from 2.1.13
- replace https://github.com/airlift/airbase/pull/193 and impl feedback

Update git commit id plugin to 3.0.1

---

CHANGES.md
airbase/pom.xml

This fixes resolution of system scope dependencies.
See https://github.com/HubSpot/dependency-scope-maven-plugin/issues/4

Update Dependency Scope plugin to 0.10

---

airbase/pom.xml

https://github.com/airlift/airbase/pull/216#issuecomment-620170052

Add clarification comment

---

CHANGES.md
airbase-policy/src/main/resources/checkstyle/airbase-checks.xml

Require static imports for Preconditions and Verify

Require static imports for Preconditions and Verify

---

CHANGES.md
airbase-policy/src/main/resources/checkstyle/airbase-checks.xml

Require static imports for immutable collection collectors

Require static imports for immutable collection collectors

---

CHANGES.md
airbase/pom.xml

This includes fix for https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/524

Upgrade git-commit-id plugin to 4.0.3

---

CHANGES.md
airbase/pom.xml

New BVal brings performance improvements and bugfixes
Guava promotes some of the `@Beta` APIs to stable and brings/deprecate some
AssertJ core brings fixes, improvements and new assertions
maven-compiler-plugin includes bugfixes
Joda Time updates internal TZ database

Dependency updates

---

airbase-policy/src/main/resources/checkstyle/airbase-checks.xml

Use negative lookahead

---

airbase-policy/src/main/resources/checkstyle/airbase-checks.xml

According to https://github.com/trinodb/trino/pull/7552#discussion_r630003539.

Add method name check

---

CHANGES.md
README.md
airbase/pom.xml

Remove cglib

---

CHANGES.md
airbase/pom.xml

Update jmh to the latest version. Among Other things, it includes support for AsyncProfiler.

Update jmh to 1.32

---

CHANGES.md
airbase/pom.xml

Update modernizer to 2.3.0

---

CHANGES.md

I had an outdated version of the master branch locally and added the log under an older version.

Two changelog fixes

---

CHANGES.md
airbase/pom.xml

This new version fixes some potential vulnerabilities.

Bump Jackson version

---

CHANGES.md
airbase/pom.xml

Ref: https://github.com/basepom/duplicate-finder-maven-plugin/issues/53

Bump duplicate-finder-maven-plugin to 1.5.1

---

CHANGES.md
airbase/pom.xml

Update Jackson to the latest version available

Update jackson to 2.14.1

---

CHANGES.md
airbase-policy/src/main/resources/checkstyle/airbase-checks.xml

This fixes #327 to also suppress the check for records.

Allow redundant modifiers within records

---

CHANGES.md
airbase/pom.xml

This improves performance when running with Maven Daemon

Run compiler in same process by default

---

CHANGES.md
airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
airbase/pom.xml

Alternative approach to https://github.com/airlift/airbase/pull/355 as suggested by @electrum 
For reference: https://github.com/skuzzle/restrict-imports-enforcer-rule

Replace checkstyle illegal import rules with RestrictImports

---

README.md

Sync readme with actual dependencies

---

CHANGES.md
airbase/pom.xml

Update surefire-maven-plugin to 3.1.2

---

.github/workflows/ci.yml
CHANGES.md
airbase/pom.xml

Compilation tested against both Trino and Airlift

Update dependencies & plugins

---

CHANGES.md
airbase/pom.xml

Update maven plugins

---

CHANGES.md
airbase/pom.xml

https://github.com/martint/jmxutils/pull/56

jmxutils 1.26

---

CHANGES.md
airbase/pom.xml

Tested locally with Trino. Includes https://github.com/airlift/airbase/pull/392

Upgrade plugins & dependencies

---

CHANGES.md
airbase/pom.xml

cc @electrum @martint @findepi

Update checkstyle to 10.16.0 & other deps

---

airbase-policy/pom.xml

see https://github.com/jvm-repo-rebuild/reproducible-central/tree/master/content/io/airlift/airbase

fix Reproducible Builds issue

---

airbase/pom.xml

Remove eclipse compiler profile

---

airbase/pom.xml

Use separate property for alpha OpenTelemetry packages version

---

airbase/pom.xml

Add opentelemetry-semconv to managed dependencies

---

airbase/pom.xml

Add Jetty dependency

---

airbase/pom.xml

Fix Jetty bom import

---

.github/workflows/release.yml
jreleaser.yml

Use proper commit for release with jrealeaser

---

airbase/pom.xml

This is needed to transform module-info.java files

Upgrade ASM in maven-compiler-plugin

---

.github/workflows/release.yml

Test out early access JReleaser github action

---

airbase-policy/pom.xml
airbase/pom.xml
pom.xml

The last release flow broke due to jreleaser changes that I wanted to try out - artifacts were pushed but commits were not.

Fix master branch

---

.github/workflows/release.yml

Revert "Test out early access JReleaser github action"

---

airbase/pom.xml

Revert "Bump dep.jetty.version from 12.0.14 to 12.0.15"

---

airbase/pom.xml

Use new airlift launcher

---

airbase/pom.xml

Previously the version 1.9.3 was used which is incompatible with JUnit 1.12.0

Update JUnit platform

---

airbase/pom.xml

Bump dep.jetty.version from 12.0.18 to 12.1.0.alpha2

---

airbase/pom.xml

This reverts commit 3df812f898833a4ad6b244c862c67cc15da91b7b.

Revert "Bump dep.jetty.version from 12.0.18 to 12.1.0.alpha2"

---

airbase/pom.xml

Revert "Bump com.fasterxml.jackson:jackson-bom from 2.18.3 to 2.19.0"

---

airbase-policy/pom.xml

Add project.name to airbase-policy

---

airbase/pom.xml

Add guice & asm dependencies

---

airbase/pom.xml
pom.xml

Use legacy altDeploymentRepository format for better compatibility

---

airbase/pom.xml

https://github.com/apache/maven-javadoc-plugin/issues/1258

Do not detect offline links

---

airbase/pom.xml

Update jetty environment to ee11

---

airbase/pom.xml

https://github.com/FasterXML/jackson/wiki/Jackson-Release-3.0

Add Jackson 3.x bom
